apiVersion: v1
name: fission-core
version: v0.2.0-20170822
description: Fission is a fast serverless framework for Kubernetes.
keywords:
- fission
- serverless
home: http://fission.io/
maintainers:
  - name: Sanket Sudake
    email: sanketsudake@gmail.com
  - name: Soam Vasani
    email: soamvasani@platform9.com
  - name: Ta Ching Chen
    email: contact@tachingchen.com
engine: gotpl
